spring:
  datasource:
<<<<<<< HEAD
    driverClassName: org.postgresql.Driver
=======
    driverClassName: org.postgresql.Driver    
>>>>>>> origin/master
    url: jdbc:postgresql://172.16.64.133/tcs
    username: modulo4
    password: modulo4

server:
   port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: https://modulo-alumno-eureka.herokuapp.com/eureka #http://localhost:8761/eureka/
  instance:
    hostname: localhost
    nonSecurePort: 8080

banner:
  location: classpath:/example/banner.txt
